language: node_js
node_js:
  - "6.9"
  - "7.0"
  - "8.0"
# env:
#   - CXX=g++-4.8
dist: trusty
addons:
  chrome: stable
  # apt:
  #   sources:
  #     - ubuntu-toolchain-r-test
  #   packages:
  #     - g++-4.8
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - yarn

script:
  - yarn run lint
# - yarn run test:ci
# - yarn run e2e
