language: node_js
node_js:
  - "4.0"
  - "5.0"
  - "6.0"
  - "7.0"
  - "8.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
    chrome: stable
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - yarn

script:
  - yarn run lint
  - yarn test --browsers ChromeHeadless --code-coverage true
#  - yarn run e2e
